# Generated by Django 5.2 on 2025-04-17 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.PositiveSmallIntegerField()),
                ('floor', models.PositiveSmallIntegerField()),
                ('dorm', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('admission_number', models.PositiveIntegerField(null=True)),
                ('university_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=35)),
                ('middle_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35, null=True)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'MALE')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('section', models.CharField(max_length=3, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/images/')),
                ('matric_pdf', models.FileField(blank=True, null=True, upload_to='students/pdfs')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.batch')),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.dorm')),
            ],
        ),
    ]
