# Generated by Django 5.2 on 2025-04-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dorm',
            old_name='dorm',
            new_name='room',
        ),
    ]
